'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <Link 
          href="/"
          className="inline-flex items-center text-blue-400 hover:text-blue-300 transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>

        <div className="text-center mb-12">
          <h1 className="text-6xl font-bold mb-4 bg-gradient-to-r from-blue-400 via-purple-400 to-emerald-400 bg-clip-text text-transparent">
            ThirdLayer Copilot
          </h1>
          <h2 className="text-4xl font-bold">Privacy Policy</h2>
          <p className="text-gray-400 mt-4">
            Last updated: June 16, 2025
          </p>
        </div>

        <div className="prose prose-invert max-w-none">
          <p className="text-gray-300 mb-8">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>

          <p className="text-gray-300 mb-8">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          </p>

          <section className="mb-12">
            <h2 className="text-3xl font-semibold mb-6">Interpretation and Definitions</h2>
            <h3 className="text-2xl font-semibold mb-4">Interpretation</h3>
            <p className="text-gray-300 mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-2xl font-semibold mb-4">Definitions</h3>
            <p className="text-gray-300 mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ThirdLayer Copilot.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: California, United States</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to ThirdLayer Copilot, accessible from https://thirdlayer-copilot.vercel.app/</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-semibold mb-6">Collecting and Using Your Personal Data</h2>
            <h3 className="text-2xl font-semibold mb-4">Types of Data Collected</h3>
            
            <h4 className="text-xl font-semibold mb-4">Personal Data</h4>
            <p className="text-gray-300 mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-xl font-semibold mb-4 mt-8">Usage Data</h4>
            <p className="text-gray-300 mb-4">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-gray-300 mb-4">
              Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-semibold mb-6">Tracking Technologies and Cookies</h2>
            <p className="text-gray-300 mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-semibold mb-6">Use of Your Personal Data</h2>
            <p className="text-gray-300 mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>For the performance of a contract</li>
              <li>To contact You</li>
              <li>To provide You with news and updates</li>
              <li>To manage Your requests</li>
              <li>For business transfers</li>
              <li>For other purposes</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-3xl font-semibold mb-6">Contact Us</h2>
            <p className="text-gray-300">
              If you have any questions about this Privacy Policy, You can contact us:
              <br />
              <a href="mailto:jiwonjeong414@gmail.com" className="text-blue-400 hover:text-blue-300">
                jiwonjeong414@gmail.com
              </a>
            </p>
          </section>

          <p className="text-gray-400 text-sm mt-12">
            Generated using TermsFeed Privacy Policy Generator
          </p>
        </div>
      </div>
    </div>
  );
} 